-- SELECT COUNT(DISTINCT id), COUNT(id), COUNT(DISTINCT codigo_contrato), COUNT(codigo_contrato) from main.contratos_compras
-- SELECT
--     nm_candidato,
--     nr_cpf_candidato,
--     sum(vr_despesa_contratada)
-- from
--     main.despesas_contratadas_candidatos
-- GROUP BY
--     nm_candidato,
--     nr_cpf_candidato
-- order by
--     sum(vr_despesa_contratada) desc
-- limit
--     100
-- SELECT
--     nm_candidato,
--     count(*),
--     sum(vr_despesa_contratada)
-- from
--     main.despesas_contratadas_candidatos
-- where
--     nm_candidato = 'GUILHERME CASTRO BOULOS'
-- GROUP BY
--     nm_candidato
-- order by
--     sum(vr_despesa_contratada) desc

select count(DISTINCT nm_candidato) from main.despesas_contratadas_candidatos
-- 37404647192.12283